version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-config.yml:/etc/otel-collector-config.yml
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - "4317:4317"  # Puerto para OTLP gRPC
      - "55681:55681"  # Puerto para OTLP HTTP

  opentelemetry-app:
    build: .
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Interfaz de Jaeger
      - "14268:14268"  # Puerto para recibir trazas
      - "14250:14250"
      - "6831:6831/udp"
      - "6832:6832/udp"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411