version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55681:55681"
      - "8888:8888"
    volumes:
      - ./otel-config.yml:/etc/otel-collector-config.yml
    command: ["--config=/etc/otel-collector-config.yml"]

  opentelemetry-app:
    build: .
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317  # URL correcta
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
