receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"  # Cambiado de localhost a 0.0.0.0
      http:
        endpoint: "0.0.0.0:4318"  # Cambiado de localhost a 0.0.0.0

exporters:
  debug: {}
  otlp:
    endpoint: "http://otel-collector:4317"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]